[package]
name = "block_db"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.7.2"
libc = "0.2.167"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
